services:
  - type: web
    name: imperio-espetos-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ANTHROPIC_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PIN_DONO
        sync: false
      - key: PIN_CAIXA
        sync: false
